return {
  -- {
  --   "folke/tokyonight.nvim",
  --   opts = {
  --     transparent = true,
  --     styles = {
  --       sidebars = "transparent",
  --       floats = "transparent",
  --     },
  --   },
  -- },
  --   {
  --     "projekt0n/github-nvim-theme",
  --   },
  --   {
  --     "LazyVim/LazyVim",
  --     opts = {
  --       colorscheme = "github_dark_default",
  --     },
  --   },
}
