[general]
import = [
    "~/.config/alacritty/themes/rose_pine.toml"
]

[window]
padding = { x = 2, y = 2 }
option_as_alt = "OnlyLeft"

[font]
normal = { family = "Iosevka Nerd Font Mono" }
size = 22.0
